### ISSUE TITLE
[WinError 10061] on script example

### ISSUE THREAD

**Issue by crippler123** [raczben/pylinx#1]
Hi, I tried to run the example script 

I get

[WinError 10061] No connection could be made because the target machine actively refused it

**Comment by raczben** [comment]
Hi,

Can you write more detail? (Version of OS, Python, Vivado...)
Please copy the full stack trace.

I guess that this line fails: `xsct = Xsct('localhost', PORT)`
Please run the example script line by line.
Please check that `hw_server` is running after enter this line: `xsct_server = XsctServer(win_xsct_executable, port=PORT, verbose=False)`

**Comment by crippler123** [comment]
Hi, thanks for quick answer

Version of OS - windows 10
python - 3.7
vivado - 2018.3

I guess that this line fails: `xsct = Xsct('localhost', PORT)`  - in deed

Please run the example script line by line - already done, fails on Xsct connect method on `self._socket.connect((host, port))`

lease check that hw_server is running after enter this line - how?

**Comment by raczben** [comment]
> *fails on Xsct connect method on self._socket.connect((host, port))*

Yes, this leads me that `xsdbserver` isn't running (I was wrong with the hw_server). xsdbserver is part of Vivado, which can be started in `xsct`/`xsdb` console.

First please turn on logging by setting `PYSCT_LOGGER_LEVEL` environment variable to `INFO`. Enter the following command before start the python interpreter: `set PYSCT_LOGGER_LEVEL=INFO`

The  `xsdbserver` is started in [this line](https://github.com/raczben/pylinx/blob/300245f0edca466d9c2520825555979a31fa3b13/pylinx/core.py#L79). If you turned on logging it should print the starter command like this:

```2020-07-27 10:42:28,346 - core.py::start_server - INFO - Starting xsct server: C:\Xilinx\SDK\2017.4\bin\xsct.bat -eval "xsdbserver start -port 3121" -interactive```

Please run this command manually, and check the result. It should start the xsdbserver, and should not return. An interactive shell should be remained open.

Please open a putty. And try to connect to xsdbserver's port in *raw* mode

![putty](https://user-images.githubusercontent.com/14052809/88522563-d32bf800-cff6-11ea-8698-1e1409d58e17.png)

Try to enter some xsct command.

Please send me when you have failed.

**Comment by crippler123** [comment]
Hi

I ran with debugger,
I do see the log message:  `2020-07-27 14:04:38,323 - core.py::start_server - INFO - Starting xsct server:  C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 3121" -interactive`
Traceback (most recent call last)
however the start server function now fails with
```OSError: [WinError 87] The parameter is incorrect```

**Comment by raczben** [comment]
Hi,

### 1. More detail
Can you send more detailed traces and logs? (I mean the full trace of the `[WinError 87]` error.)

### 2. xsdbserver manually
Did you try to launch the xsdbserver manually? (As I suggested earlier) Please tell me the results.
Note, that the structure of pylinx is the following:

1. Start the xsdbserver

    1. Launch XSCT/XSDB console
    2. Start xsdbserver in this console

2. Connect to xsdbserver 

    1. Open a raw socket
    2. Send commands and parse results

The first step (*starting the xsdbserver*) can be done manually. What's more, I prefer to do this manually.

### 3. xsdbserver manually (from python)
Please open a simple python interpreter and enter the following commands:

```python
cmd = 'C:\\Xilinx\\SDK\\2018.3\\bin\\xsct.bat -eval "xsdbserver start -port 3121" -interactive'
subprocess.Popen(cmd)

# and try this one:

subprocess.Popen(cmd, stdout=None)
```

(I didn't use it with Vivado 2018, but it should not be a problem.)

**Comment by crippler123** [comment]
Hi

1. full trace:
```console
C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\python.exe C:/pythonProjects/Test_xsct/test_xsct.py
4.0.0
INFO
2020-08-11 15:56:20,184 - core.py::start_server - INFO - Starting xsct server:  C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 65000" -interactive
Traceback (most recent call last):
  File "C:/pythonProjects/Test_xsct/test_xsct.py", line 10, in <module>
    xsct_server = XsctServer(win_xsct_executable, port=p, verbose=False)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 77, in __init__
    self.start_server(xsct_executable, port, verbose)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 96, in start_server
    self._xsct_server = subprocess.Popen(start_command, stdout=stdout)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 87] The parameter is incorrect

Process finished with exit code 1
```

2. when running manually, I get
```
C:\temp\tcl_scripts>C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 3121" -interactive
start was unexpected at this time.
```

3. when running xsdbserver manually (from python)
I get in python trace:
```
4.0.0
INFO

Process finished with exit code 0
```

and when trying to connect with putty (as client),
```
I get Network error: Connection refused
```

**Comment by crippler123** [comment]
Hi

1. full trace:
C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\python.exe C:/pythonProjects/Test_xsct/test_xsct.py
4.0.0
INFO
2020-08-11 15:56:20,184 - core.py::start_server - INFO - Starting xsct server:  C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 65000" -interactive
Traceback (most recent call last):
  File "C:/pythonProjects/Test_xsct/test_xsct.py", line 10, in <module>
    xsct_server = XsctServer(win_xsct_executable, port=p, verbose=False)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 77, in __init__
    self.start_server(xsct_executable, port, verbose)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 96, in start_server
    self._xsct_server = subprocess.Popen(start_command, stdout=stdout)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 87] The parameter is incorrect

Process finished with exit code 1


2. when running manually, I get
C:\temp\tcl_scripts>C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 3121" -interactive
start was unexpected at this time.


3. when running xsdbserver manually (from python)
I get in python trace:
4.0.0
INFO

Process finished with exit code 0


and when trying to connect with putty (as client),

I get Network error: Connection refused

**Comment by crippler123** [comment]
Hi

1. full trace:
C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\python.exe C:/pythonProjects/Test_xsct/test_xsct.py
4.0.0
INFO
2020-08-11 15:56:20,184 - core.py::start_server - INFO - Starting xsct server:  C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 65000" -interactive
Traceback (most recent call last):
  File "C:/pythonProjects/Test_xsct/test_xsct.py", line 10, in <module>
    xsct_server = XsctServer(win_xsct_executable, port=p, verbose=False)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 77, in __init__
    self.start_server(xsct_executable, port, verbose)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 96, in start_server
    self._xsct_server = subprocess.Popen(start_command, stdout=stdout)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 87] The parameter is incorrect

Process finished with exit code 1


2. when running manually, I get
C:\temp\tcl_scripts>C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 3121" -interactive
start was unexpected at this time.


3. when running xsdbserver manually (from python)
I get in python trace:
4.0.0
INFO

Process finished with exit code 0


and when trying to connect with putty (as client),

I get Network error: Connection refused

**Comment by crippler123** [comment]
Hi

1. full trace:
C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\python.exe C:/pythonProjects/Test_xsct/test_xsct.py
4.0.0
INFO
2020-08-11 15:56:20,184 - core.py::start_server - INFO - Starting xsct server:  C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 65000" -interactive
Traceback (most recent call last):
  File "C:/pythonProjects/Test_xsct/test_xsct.py", line 10, in <module>
    xsct_server = XsctServer(win_xsct_executable, port=p, verbose=False)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 77, in __init__
    self.start_server(xsct_executable, port, verbose)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 96, in start_server
    self._xsct_server = subprocess.Popen(start_command, stdout=stdout)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 87] The parameter is incorrect

Process finished with exit code 1


2. when running manually, I get
C:\temp\tcl_scripts>C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 3121" -interactive
start was unexpected at this time.


3. when running xsdbserver manually (from python)
I get in python trace:
4.0.0
INFO

Process finished with exit code 0


and when trying to connect with putty (as client),

I get Network error: Connection refused

**Comment by crippler123** [comment]
Hi

1. full trace:
C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\python.exe C:/pythonProjects/Test_xsct/test_xsct.py
4.0.0
INFO
2020-08-11 15:56:20,184 - core.py::start_server - INFO - Starting xsct server:  C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 65000" -interactive
Traceback (most recent call last):
  File "C:/pythonProjects/Test_xsct/test_xsct.py", line 10, in <module>
    xsct_server = XsctServer(win_xsct_executable, port=p, verbose=False)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 77, in __init__
    self.start_server(xsct_executable, port, verbose)
  File "C:\Users\nyehuda\AppData\Roaming\Python\Python37\site-packages\pylinx\core.py", line 96, in start_server
    self._xsct_server = subprocess.Popen(start_command, stdout=stdout)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\nyehuda\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 87] The parameter is incorrect

Process finished with exit code 1


2. when running manually, I get
C:\temp\tcl_scripts>C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 3121" -interactive
start was unexpected at this time.


3. when running xsdbserver manually (from python)
I get in python trace:
4.0.0
INFO

Process finished with exit code 0


and when trying to connect with putty (as client),

I get Network error: Connection refused

**Comment by raczben** [comment]
There is something with launching the `xsdbserver`. The `*** was unexpected at this time.` error message comes from Windows CMD
(similar like [this ](https://stackoverflow.com/q/7769591/2506522))
It seems that the double quote is `"` is not recognized. More precisely, the string between the two double quotes is not recognized as one string.

The root cause can be character coding or terminal setting, but I don't know.

Here is a **workaround**: Start the xsct manually: `C:\Xilinx\SDK\2018.3\bin\xsct.bat`, then enter the `xsdbserver start -port 3121` command in it to start the xsdbserver

**Comment by crippler123** [comment]
Hi

1. I've performed the work around and the server started successfully.

2. I've created a client via putty, and connection vas success.
    However,  I could send only one command. At the other commands I've sent, 
    I've got nothing but a blank screen (in putty)


3. I've started a client in python via pylinx    (  xsct = Xsct(host=host, port=port)   ), and succeed to connect to server.
    I've also managed to send commands (via do function), and receive propper answeres.


How shall we proceed?

**Comment by crippler123** [comment]
Hi

1. I've performed the work around and the server started successfully.

2. I've created a client via putty, and connection vas success.
    However,  I could send only one command. At the other commands I've sent, 
    I've got nothing but a blank screen (in putty)


3. I've started a client in python via pylinx    (  xsct = Xsct(host=host, port=port)   ), and succeed to connect to server.
    I've also managed to send commands (via do function), and receive propper answeres.


How shall we proceed?

**Comment by raczben** [comment]
I guess you can use pylinx now, however, I understand, that this manual workaround is annoying.

The `xsdbserver` starter command should be fixed ( `C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "xsdbserver start -port 3121" -interactive` ), but this is a Windows CMD and/or Xilinx's SDK issue. I still guess character encoding or similar.

 1. What is your Windows' language / region? 
 2. Try the following commands and send the results:

```bat
rem # Print the PID of the SDK and open an interactive terminal
C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "puts [pid]" -interactive`

rem # Print the PID of the SDK and exit
C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "puts [pid]"

rem # More commands:
C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "puts [pid]; puts [pid]"

rem # More commands:
C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "puts [pid]; puts [pid]" -interactive
```

**Comment by crippler123** [comment]
1. English/US
2. 

C:\Xilinx\SDK\2018.3\bin\xsct.bat -eval "puts [pid]" -interactive`

output: [pid]""=="" was unexpected at this time.

**Comment by raczben** [comment]
Oh, I said that Vivado 2018.3 should work, but I made a mistake. 

Checkout this thread:
https://forums.xilinx.com/t5/Embedded-Development-Tools/xsct-from-command-line-can-t-parse-tcl-command-2018-2/td-p/891676

I think this is the same issue...

**Comment by crippler123** [comment]
Hi
1. I don't work with Vivado, but with Xlinx SDK.

2. I don't understand how to implement the thread example, in our example

**Comment by raczben** [comment]
> I don't work with Vivado, but with Xlinx SDK.

Ok, but please checkout the link to the Xilinx forum, which describes the same issue. This is a Xilinx bug I cannot solve the root cause.
So I will close this thread.

Another workaround (which can be built into pylinx) is to use *tclscript* instead of the *eval*:

save the following file as `startserver.tcl`
```tcl
#startserver.tcl

xsdbserver start -port 3121
```

Then start the xsct with the following command:
```
C:\Xilinx\SDK\2018.3\bin\xsct.bat startserver.tcl
```

If it works replace the server-starter line in pylinx script to `C:\Xilinx\SDK\2018.3\bin\xsct.bat startserver.tcl`

**Comment by crippler123** [comment]
Hi

Now it works  (using the plinx server and client), with or without tcl script

It seems that the problem was an unnecessary space in xsct_path

instead of win_xsct_executable = r'C:\Xilinx\SDK\2018.3\bin\xsct.bat'
I wrote win_xsct_executable = r' C:\Xilinx\SDK\2018.3\bin\xsct.bat'  (!!!!)

changed, and it seems to work.

you can close the issue.


PS.

in the API

I would reccoment  in the server/client class, to do the connection in a seperate method

instead the constructor.


and to add a method in server, that checks if server is already on.


Thanks.

**Comment by crippler123** [comment]
Hi
It seems to not working properly again.
when running server, I keep getting the
"start was unexpected at this time"  message ( due to "" issue in terminal)

can you enter the tcl workaround?

**Comment by crippler123** [comment]
Hi
It seems to not working properly again.
when running server, I keep getting the
"start was unexpected at this time"  message ( due to "" issue in terminal)

can you enter the tcl workaround?

**Comment by crippler123** [comment]
Meanwhile I preformed the workaround in my application,
when I try to call do function with command,
I get time out exception
